services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - '54333:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U chatuser -d chatapp']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://chatuser:chatpass@db:5432/chatapp
      NODE_ENV: production
      JWT_SECRET: supersecret
    ports:
      - '3000:3000'
    command: ['sh', '-c', 'npx prisma migrate deploy && npm run start:prod']
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - main
volumes:
  db_data:

networks:
  main:
    driver: bridge
    name: chatapp_network
